services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: spring-backend
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: html-frontend
    restart: unless-stopped
    depends_on:
      - backend
